
package clientREST;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Teams", targetNamespace = "http://sunnyREST/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Teams {


    /**
     * 
     * @param arg0
     * @return
     *     returns clientREST.Team
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeam", targetNamespace = "http://sunnyREST/", className = "clientREST.GetTeam")
    @ResponseWrapper(localName = "getTeamResponse", targetNamespace = "http://sunnyREST/", className = "clientREST.GetTeamResponse")
    public Team getTeam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<clientREST.Team>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTeams", targetNamespace = "http://sunnyREST/", className = "clientREST.GetTeams")
    @ResponseWrapper(localName = "getTeamsResponse", targetNamespace = "http://sunnyREST/", className = "clientREST.GetTeamsResponse")
    public List<Team> getTeams();

}
